sonar.projectKey=inventario-php
sonar.projectName=Inventario PHP
sonar.projectVersion=1.0
sonar.sources=index.php,controllers,models,lib,views
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=assets/**,vendor/**,storage/**,docs/**
sonar.php.coverage.reportPaths=coverage.xml
